#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # Actualizar la caché de archivos .desktop
    if [ -x /usr/bin/update-desktop-database ]; then
        update-desktop-database -q /usr/share/applications || true
    fi
    
    # Actualizar la caché de iconos
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
        gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true
    fi
fi

exit 0
